# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /opt/clion/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vegi/Documents/code/Projects/Vsh

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vegi/Documents/code/Projects/Vsh

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/clion/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/clion/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vegi/Documents/code/Projects/Vsh/CMakeFiles /home/vegi/Documents/code/Projects/Vsh//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vegi/Documents/code/Projects/Vsh/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vsh

# Build rule for target.
vsh: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vsh
.PHONY : vsh

# fast build rule for target.
vsh/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/build
.PHONY : vsh/fast

src/args.o: src/args.c.o
.PHONY : src/args.o

# target to build an object file
src/args.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/args.c.o
.PHONY : src/args.c.o

src/args.i: src/args.c.i
.PHONY : src/args.i

# target to preprocess a source file
src/args.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/args.c.i
.PHONY : src/args.c.i

src/args.s: src/args.c.s
.PHONY : src/args.s

# target to generate assembly for a file
src/args.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/args.c.s
.PHONY : src/args.c.s

src/builtins.o: src/builtins.c.o
.PHONY : src/builtins.o

# target to build an object file
src/builtins.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/builtins.c.o
.PHONY : src/builtins.c.o

src/builtins.i: src/builtins.c.i
.PHONY : src/builtins.i

# target to preprocess a source file
src/builtins.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/builtins.c.i
.PHONY : src/builtins.c.i

src/builtins.s: src/builtins.c.s
.PHONY : src/builtins.s

# target to generate assembly for a file
src/builtins.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/builtins.c.s
.PHONY : src/builtins.c.s

src/execute.o: src/execute.c.o
.PHONY : src/execute.o

# target to build an object file
src/execute.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/execute.c.o
.PHONY : src/execute.c.o

src/execute.i: src/execute.c.i
.PHONY : src/execute.i

# target to preprocess a source file
src/execute.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/execute.c.i
.PHONY : src/execute.c.i

src/execute.s: src/execute.c.s
.PHONY : src/execute.s

# target to generate assembly for a file
src/execute.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/execute.c.s
.PHONY : src/execute.c.s

src/history.o: src/history.c.o
.PHONY : src/history.o

# target to build an object file
src/history.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/history.c.o
.PHONY : src/history.c.o

src/history.i: src/history.c.i
.PHONY : src/history.i

# target to preprocess a source file
src/history.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/history.c.i
.PHONY : src/history.c.i

src/history.s: src/history.c.s
.PHONY : src/history.s

# target to generate assembly for a file
src/history.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/history.c.s
.PHONY : src/history.c.s

src/jobs.o: src/jobs.c.o
.PHONY : src/jobs.o

# target to build an object file
src/jobs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/jobs.c.o
.PHONY : src/jobs.c.o

src/jobs.i: src/jobs.c.i
.PHONY : src/jobs.i

# target to preprocess a source file
src/jobs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/jobs.c.i
.PHONY : src/jobs.c.i

src/jobs.s: src/jobs.c.s
.PHONY : src/jobs.s

# target to generate assembly for a file
src/jobs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/jobs.c.s
.PHONY : src/jobs.c.s

src/ls.o: src/ls.c.o
.PHONY : src/ls.o

# target to build an object file
src/ls.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/ls.c.o
.PHONY : src/ls.c.o

src/ls.i: src/ls.c.i
.PHONY : src/ls.i

# target to preprocess a source file
src/ls.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/ls.c.i
.PHONY : src/ls.c.i

src/ls.s: src/ls.c.s
.PHONY : src/ls.s

# target to generate assembly for a file
src/ls.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/ls.c.s
.PHONY : src/ls.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/main.c.s
.PHONY : src/main.c.s

src/parse.o: src/parse.c.o
.PHONY : src/parse.o

# target to build an object file
src/parse.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/parse.c.o
.PHONY : src/parse.c.o

src/parse.i: src/parse.c.i
.PHONY : src/parse.i

# target to preprocess a source file
src/parse.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/parse.c.i
.PHONY : src/parse.c.i

src/parse.s: src/parse.c.s
.PHONY : src/parse.s

# target to generate assembly for a file
src/parse.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/parse.c.s
.PHONY : src/parse.c.s

src/prompt.o: src/prompt.c.o
.PHONY : src/prompt.o

# target to build an object file
src/prompt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/prompt.c.o
.PHONY : src/prompt.c.o

src/prompt.i: src/prompt.c.i
.PHONY : src/prompt.i

# target to preprocess a source file
src/prompt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/prompt.c.i
.PHONY : src/prompt.c.i

src/prompt.s: src/prompt.c.s
.PHONY : src/prompt.s

# target to generate assembly for a file
src/prompt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/prompt.c.s
.PHONY : src/prompt.c.s

src/rawio.o: src/rawio.c.o
.PHONY : src/rawio.o

# target to build an object file
src/rawio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/rawio.c.o
.PHONY : src/rawio.c.o

src/rawio.i: src/rawio.c.i
.PHONY : src/rawio.i

# target to preprocess a source file
src/rawio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/rawio.c.i
.PHONY : src/rawio.c.i

src/rawio.s: src/rawio.c.s
.PHONY : src/rawio.s

# target to generate assembly for a file
src/rawio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/rawio.c.s
.PHONY : src/rawio.c.s

src/utils.o: src/utils.c.o
.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vsh.dir/build.make CMakeFiles/vsh.dir/src/utils.c.s
.PHONY : src/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... vsh"
	@echo "... src/args.o"
	@echo "... src/args.i"
	@echo "... src/args.s"
	@echo "... src/builtins.o"
	@echo "... src/builtins.i"
	@echo "... src/builtins.s"
	@echo "... src/execute.o"
	@echo "... src/execute.i"
	@echo "... src/execute.s"
	@echo "... src/history.o"
	@echo "... src/history.i"
	@echo "... src/history.s"
	@echo "... src/jobs.o"
	@echo "... src/jobs.i"
	@echo "... src/jobs.s"
	@echo "... src/ls.o"
	@echo "... src/ls.i"
	@echo "... src/ls.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parse.o"
	@echo "... src/parse.i"
	@echo "... src/parse.s"
	@echo "... src/prompt.o"
	@echo "... src/prompt.i"
	@echo "... src/prompt.s"
	@echo "... src/rawio.o"
	@echo "... src/rawio.i"
	@echo "... src/rawio.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

